app:
  name: travel-planner
  port: 42080
database:
  host: localhost
  port: 3306
  user: root
  password: secret
llm-ark:
  default-model: doubao-seed-1-6-flash-250828
  api-key: 773eac6a-e077-42bd-bd1c-e9836bd5c6b8
  base-url: https://ark.cn-beijing.volces.com/api/v3
embedding-ark:
  default-model: doubao-embedding-text-240715
  api-key: 773eac6a-e077-42bd-bd1c-e9836bd5c6b8
  base-url: https://ark.cn-beijing.volces.com/api/v3
llm-modelscope:
  default-model: deepseek-ai/DeepSeek-V3.1
  api-key: ms-051829f9-88bc-48ac-9e0f-b5e0a595a3c4
  base-url: https://api-inference.modelscope.cn/v1
milvus:
  addr: localhost:19530
