// Code generated by hertz generator.

package main

import (
	"context"
	"log"
	"travel/biz/config"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/joho/godotenv"
	"github.com/spf13/viper"
)

func main() {
	ctx := context.Background()
	loadConfig(ctx)
	h := server.Default(server.WithHostPorts("0.0.0.0:" + viper.GetString("app.port")), server.WithStreamBody(true))

	register(h)
	h.Spin()
}

func loadConfig(ctx context.Context) {
	loadEnv()
	loadViper()
	config.InitDatabase(ctx)
	config.InitOssClient(ctx)
	config.InitModel(ctx)
	config.InitMcpTools(ctx)
	config.InitVDateBase(ctx)
	config.InitRetriever(ctx)
	config.InitIndexer(ctx)
}

func loadViper() {
	// configure file name
	viper.SetConfigName("config")
	// configure file type
	viper.SetConfigType("yaml")
	// configure viper to read from the current directory
	viper.AddConfigPath(".") // current directory
	if err := viper.ReadInConfig(); err != nil {
		log.Fatalf("Error reading config file: %v", err)
	}
}

func loadEnv() {
	// 加载 .env 文件
	if err := godotenv.Load(); err != nil {
		log.Printf("Warning: Error loading .env file: %v", err)
	}
}
