// Code generated by hertz generator.

package main

import (
	"context"
	"travel/biz/agent"
	"travel/biz/config"
	"travel/biz/middleware"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/logger/accesslog"
	"github.com/spf13/viper"
)

func main() {
	ctx := context.Background()
	config.InitAll(ctx)
	agent.InitAll(ctx)
	middleware.InitAll()
	h := server.Default(server.WithHostPorts(":" + viper.GetString("app.port")))
	h.Use(accesslog.New())

	register(h)
	h.Spin()
}


