// Code generated by hertz generator.

package main

import (
	"context"
	"travel/biz/config"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/spf13/viper"
)

func main() {
	ctx := context.Background()
	config.InitAll(ctx)
	h := server.Default(server.WithHostPorts("0.0.0.0:" + viper.GetString("app.port")), server.WithStreamBody(true))

	register(h)
	h.Spin()
}


